set-option -g mouse on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

# Mac
set -s copy-command 'pbcopy'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'

bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R
